name: AutoSignIn
on:
  push:
  schedule:
    - cron: '5 10 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
            python-version: 3.9
      - name: Install
        run:
            pip install -r requirements.txt
      - name: Install playwright
        run:
            playwright install
      - name: Run
        env:
            ACCOUNT: ${{secrets.ACCOUNT}}
        run: |
            python main.py
